trigger:
- main  # Change this if your branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrServiceConnection: 'ACR'  # Replace with your actual ACR service connection name
  azureRmServiceConnection: 'AzureRM'  # Replace with your actual Azure RM service connection name
  appName: 'Hack4job'
  containerRegistry: 'hack4job.azurecr.io'
  imageName: 'kakaraladharanihonyaapp'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: login
        containerRegistry: $(acrServiceConnection)  # Corrected reference

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        repository: $(imageName)  # Fix: Repository should be only the image name
        containerRegistry: $(containerRegistry)
        tags: 'latest'

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: push
        repository: $(imageName)  # Fix: Repository should be only the image name
        containerRegistry: $(containerRegistry)
        tags: 'latest'

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: $(azureRmServiceConnection)  # Corrected reference
        appName: $(appName)
        containers: $(containerRegistry)/$(imageName):latest

